/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.alenin;

import com.google.common.math.IntMath;

@SuppressWarnings("java:S106")
public class HelloOtus {
    public static void main(String... args) {
        int a = 24;
        int b = 18;

        int gcd = IntMath.gcd(a, b);
        System.out.println("НОД(" + a + ", " + b + ") = " + gcd);
    }
}
